{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.parentName }}
  labels:
    {{- include "finedgar.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.port }}
      hostname: {{ .Values.gateway.host | quote }}
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "finedgar.fullname" . }}-web
  labels:
    {{- include "finedgar.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentName }}
  hostnames:
    - {{ .Values.gateway.host | quote }}
  rules:
    - backendRefs:
        - name: {{ include "finedgar.fullname" . }}-web
          port: 80
{{- end }}
