apiVersion: v1
kind: Service
metadata:
  name: {{ include "finedgar.fullname" . }}-ollama
  labels:
    {{- include "finedgar.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: ClusterIP
  selector:
    {{- include "finedgar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
  ports:
    - name: http
      port: {{ .Values.ollama.port }}
      targetPort: http
