{{- if .Values.observability.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "finedgar.fullname" . }}-web
  labels:
    {{- include "finedgar.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "finedgar.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.observability.metrics.serviceMonitor.interval }}
{{- end }}
