apiVersion: v1
kind: Service
metadata:
  name: {{ include "finedgar.fullname" . }}-web
  labels:
    {{- include "finedgar.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "finedgar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
